api/users/__init__.py
import logging
from api.config import Config
# logging.basicConfig(level=logging.INFO,filename="api.log",
#                     format = '%(asctime)s] %(levelname)s in %(module)s: %(message)s')
#
# logging configuration
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

formatter = logging.Formatter('%(asctime)s] %(levelname)s in %(module)s: %(message)s')

file_handler = logging.FileHandler(Config.USERS_LOGS)
file_handler.setFormatter(formatter)

logger.addHandler(file_handler)

api/users/routes.py
from flask import Blueprint, session
from . import logger


from api.models import User,Role,Key
from api.main.utils import json_formatter
from flask import make_response,jsonify,request,render_template,flash,redirect,url_for
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import login_user,current_user,login_required,logout_user

users = Blueprint("users",__name__,template_folder="templates")


@users.route("/register",methods = ['GET','POST'])
def register():
    if request.method == 'POST':
        #get input from users and process application
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        email = request.form.get('email')
        password = generate_password_hash(request.form.get('password'))

        role = request.form.get("role")
        user_args = {"firstname":firstname,
                     "lastname":lastname,
                     "email":email,
                     "password":password,
                     "role_id":role}
        user = User()

        try:
            user.add_user(**user_args)
        except:
            message = f"error occured - user {email}  may already exist"
            flash(message,'danger')
            logger.error(message)
        else:
            message = f"user with email {email}  added successfully"
            flash(message,"success")
            logger.info(message)
        finally:
            return redirect(request.referrer)

    # get roles from database and populate the registration field
    roles = Role.query.all()
    return render_template("register.html",roles = roles)




@users.route("/login", methods = ['GET','POST'])
def login():
    if request.method == "POST":
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email = email).first()
        if user and check_password_hash(user.password,password):
            login_user(user)
            logger.info(f"User {user.firstname} logged in")
            flash("You have logged in successfully",'success')
            # check the user role
            if user.user_role() == user.get_user_role():
                # get the blueprint name

                return redirect(url_for(f"{user.get_user_role()}.dashboard"))
            # if user.user_role() == "admin":
            #     return redirect(url_for("admin.dashboard"))
            # if user.user_role() == "api_user":
            #     return redirect(url_for("users.api_user_profile"))
            # if user.user_role() == "developer":
            #     return redirect(url_for('users.api_developer_profile'))

    return render_template("login.html")
        # check if this is correct
        # user = User.query.filter_by(email = email).first()
        # print(user)



@login_required
@users.route("/admin",methods =['GET','POST'])
def admin_profile():
    return f"You are logged in as an admin {current_user.email}"

@login_required
@users.route("/api_user",methods =['GET','POST'])
def api_user_profile():
    return f"You are logged in as an api_user {current_user.email}"

@login_required
@users.route("/api_developer",methods =['GET','POST'])
def api_developer_profile():
    return f"You are logged in as a developer {current_user.email}"

@login_required
@users.route("/logout")
def logout():

    logger.info(f"{current_user.email} logged out")
    logout_user()
    flash("You'hv been logged out","info")
    return redirect(url_for("users.login"))


@users.route("/password")
def forgot_password():
    return render_template('password.html')


      #get input and validate user


# @users.route("/all")
# def all_users():
#     users = []
#     response = User.query.all()
#     for user in response:
#         user = json_formatter(user)
#         users.append(user)
#     return make_response(jsonify(users),200)
#
#
# @users.route("/<int:user_id>", methods = ['GET','PUT','UPDATE','DELETE'])
# def one_user(user_id):
#
#         user = User.query.filter_by(user_id = user_id).first()
#         if user:
#             if request.method == "GET":
#                 user = json_formatter(user)
#                 return make_response(jsonify(user),200)
#
#
#             if request.method == "DELETE":
#                 db.session.delete(user)
#                 db.session.commit()
#                 return make_response("Success",200)
#
#         return make_response("The requested resource was not found", 404)
#
#
# @users.route("/add", methods = ['POST'])
# def add_user():
#     content = request.json
#     if request.method == "POST":
#     # check if user already exist
#         user = User.query.filter_by(email = content['email']).first()
#         if user is None:
#     # proceed to insert user in the database
#             new_user = User(
#                 firstname = f"{content['firstname']}",
#                 lastname = f"{content['lastname']}",
#                 password = f"{content['password']}",
#                 email = f"{content['email']}",
#                 role_id = f"{content['role_id']}")
#             db.session.add(new_user)
#             db.session.commit()
#             return make_response("user added successfully", 200)
#         return make_response("user already exists",301)
#
#
# from sqlalchemy import func
# @users.route("/count", methods=['GET'])
# def user_count():
#     if request.method == "GET":
#         users  = User.query.all()
#         row_count = len(users)
#         return make_response(jsonify(row_count))
#

api/users/templates/login.html
{% extends 'base.html' %}
{%block content%}
<div class="container-fluid ps-md-0">
  <div class="row g-0">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4">Welcome back!</h3>

              <!-- Sign In Form -->
              <form method = "POST" action = "{{url_for('users.login')}}">

                <div class="form-floating mb-3">
                  <input type="email" class="form-control" id="floatingInput" name = "email" placeholder="name@email.com">
                  <label for="floatingInput">Email Address</label>
                </div>
                <div class="form-floating mb-3">
                  <input type="password" class="form-control" id="floatingPassword"  name = "password" placeholder="password">
                  <label for="floatingPassword">Password</label>
                </div>

                <div class="form-check mb-3">
                  <input class="form-check-input" type="checkbox" value="" id="rememberPasswordCheck">
                  <label class="form-check-label" for="rememberPasswordCheck">
                    Remember password
                  </label>
                </div>

                <div class="d-grid">
                  <button class="btn btn-lg btn-primary btn-login text-capitalize fw-bold mb-2" type="submit">Login</button>
                  <div class="text-center">
                    <a class="small" href="#">Forgot password?</a>
                  </div>
                </div>





              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
{%endblock%}

api/users/templates/password.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Password Reset - SB Admin</title>
        <link href="{{url_for('static', filename = 'css/styles.css')}}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Password Recovery</h3></div>
                                    <div class="card-body">
                                        <div class="small mb-3 text-muted">Enter your email address and we will send you a link to reset your password.</div>
                                        <form>
                                            <div class="form-floating mb-3">
                                                <input class="form-control" id="inputEmail" type="email" placeholder="name@example.com" />
                                                <label for="inputEmail">Email address</label>
                                            </div>
                                            <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <a class="small" href="login.html">Return to login</a>
                                                <a class="btn btn-primary" href="login.html">Reset Password</a>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center py-3">
                                        <div class="small"><a href="register.html">Need an account? Sign up!</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2022</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src ="{{url_for('static', filename = 'js/script1.js')}}"></script>
    </body>
</html>

api/users/templates/register.html
{% extends 'base.html' %}
{%block content%}
<div class="container-fluid ps-md-0">
  <div class="row g-0">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4">Welcome!</h3>

              <!-- Sign In Form -->
              <form method = "POST" action = "{{url_for('users.register')}}">
                <div class="form-floating mb-3">
                  <input type="text" class="form-control" id="floatingInput" name = "firstname" placeholder="John">
                  <label for="floatingInput">First Name</label>
                </div>
                <div class="form-floating mb-3">
                  <input type="text" class="form-control" id="floatingInput"  name = "lastname" placeholder="Doe">
                  <label for="floatingInput">Lastname</label>
                </div>
                <div class="form-floating mb-3">
                  <input type="email" class="form-control" id="floatingInput" name = "email" placeholder="name@email.com">
                  <label for="floatingInput">Email Address</label>
                </div>
                <div class="form-floating mb-3">
                  <input type="password" class="form-control" id="floatingPassword"  name = "password" placeholder="password">
                  <label for="floatingPassword">Password</label>
                </div>



                <div class = "form-check mb-3">
                      <select class="form-select" id="inputGroupSelect01" name="role">
                        <option value="none">None</option>
                          {%for role in roles%}
                        <option value="{{role.role_id}}">{{role.name}}</option>
                          {%endfor%}
                      </select>
                </div>




<!--                 <div class = "form-check mb-3">-->
<!--                      <select class="form-select" id="inputGroupSelect01" name="flight_category">-->
<!--                        <option value="none">None</option>-->

<!--                        <option value="admin">admin</option>-->
<!--                        <option value="api_user">api_user</option>-->
<!--                        <option value="developer">developer</option>-->
<!--                    </select>-->
<!--                </div>-->



                <div class="form-check mb-3">
                  <input class="form-check-input" type="checkbox" value="" id="rememberPasswordCheck">
                  <label class="form-check-label" for="rememberPasswordCheck">
                    Remember password
                  </label>
                </div>


                <div class="d-grid">
                  <button class="btn btn-lg btn-primary btn-login text-capitalize fw-bold mb-2" type="submit">Register</button>
                  <div class="text-center">
                    <a class="small" href="#">Forgot password?</a>
                  </div>
                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
{%endblock%}