api/api_user/__init__.py
import logging
from api.config import Config
# logging.basicConfig(level=logging.INFO,filename="api.log",
#                     format = '%(asctime)s] %(levelname)s in %(module)s: %(message)s')
#
# logging configuration
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

formatter = logging.Formatter('%(asctime)s] %(levelname)s in %(module)s: %(message)s')

file_handler = logging.FileHandler(Config.API_USERS_LOGS)
file_handler.setFormatter(formatter)

logger.addHandler(file_handler)

api/api_user/routes.py
from flask import Blueprint, render_template,request,redirect,url_for,flash
from api import db, alias
from . import logger
from api.models import User, Role, App, Key, Status
from flask_login import login_required, current_user

api_user = Blueprint('api_user', __name__, template_folder='templates')


@login_required
@api_user.route('/dashboard')
def dashboard():
    if current_user.is_authenticated:
        user = current_user._get_current_object()



        # result = db.session.query(User,App,Key).select_from(User).join(App).join(Key).filter(User.user_id == 2).all()
        query_result = db.session.query(User, Role, Status, App, Key, db.func.count(App.api_keys)).select_from(User).outerjoin(Role).filter(User.user_id == user.user_id).outerjoin(Status).outerjoin(App).outerjoin(Key).group_by(App.name).all()

        total_api_keys = db.session.query(db.func.count(App.api_keys)).select_from(User).outerjoin(App).filter(User.user_id == user.user_id).outerjoin(Key).group_by(User.user_id).one()
        api_key_count = total_api_keys[0]

        return render_template("api_user_index.html", data=query_result,api_key_count = api_key_count)
    return render_template('401.html')


@login_required
@api_user.route('/add_application', methods = ['POST','GET'])
def add_application():
    user = current_user._get_current_object()

    if request.method == 'POST':
        #get input from user
        app_name = request.form.get('name')
        app_description = request.form.get('description')
        app = App(name = app_name,description = app_description,user_id = user.user_id)
        db.session.add(app)
        db.session.commit()
        flash(f'{app.name} added successfully','success')
        logger.info(f"{user.email} added application with name '{app.name}'")
        return redirect(request.referrer)

    if request.method == "GET":
        apps = db.session.query(App).select_from(App).join(User).filter(User.user_id == user.user_id).all()


         #TO BE REMOVED
        query_result = db.session.query(User, Role, Status, App, Key, db.func.count(App.api_keys)).select_from(User).outerjoin(Role).filter(User.user_id == user.user_id).outerjoin(Status).outerjoin(App).outerjoin(Key).group_by(App.name).all()

        total_api_keys = db.session.query(db.func.count(App.api_keys)).select_from(User).outerjoin(App).filter(User.user_id == user.user_id).outerjoin(Key).group_by(User.user_id).one()
        api_key_count = total_api_keys[0]
        return render_template("create_application.html",apps = apps,data = query_result)


@login_required
@api_user.route('/edit_application', methods = ['POST','GET'])
def edit_application():
    user = current_user._get_current_object()
    if request.method == 'POST':

        app_id = int(request.form.get('app'))
        name = request.form.get('name')
        description = request.form.get('description')

        app = App.query.filter_by(app_id = app_id).first()
        old_app_name = app.name
        app.name = name
        app.description = description
        db.session.commit()
        flash(f'{old_app_name} edited successfully','success')
        logger.info(f"{user.email} edited application with name '{app.name}'")

        return redirect (url_for('api_user.dashboard'))
    apps = db.session.query(App).select_from(App).join(User).filter(User.user_id == user.user_id).all()

    query_result = db.session.query(User, Role, Status, App, Key, db.func.count(App.api_keys)).select_from(User).outerjoin(Role).filter(User.user_id == user.user_id).outerjoin(Status).outerjoin(App).outerjoin(Key).group_by(App.name).all()

    total_api_keys = db.session.query(db.func.count(App.api_keys)).select_from(User).outerjoin(App).filter(User.user_id == user.user_id).outerjoin(Key).group_by(User.user_id).one()
    api_key_count = total_api_keys[0]

    return render_template('edit_application.html',apps = apps,data = query_result)



@login_required
@api_user.route('/delete_app', methods = ['POST','GET'])
def delete_app():
    input = request.form.getlist('checkbox')

    print(input)
    exit()


@login_required
@api_user.route('/add_key', methods = ['POST'])
def add_api_key():
    user = current_user._get_current_object()
    app_id = int(request.form.get('app'))
    app = App.query.filter_by(app_id = app_id).first()
    app.add_key()
    flash(f'Key added successfully to app {app.name}','success')
    logger.info(f"{user.email} added api key to application with name '{app.name}'")

    return redirect (url_for('api_user.dashboard'))


@login_required
@api_user.route('/edit_key', methods = ['POST'])
def edit_api_key():
    user = current_user._get_current_object()
    if request.method == "POST" and request.form.get('key'):
        old_keys = request.form.getlist('checkbox')
        new_key = request.form.get('key')
        old_key = int(old_keys[0])
        app = db.session.query(App).select_from(App).join(Key).filter(Key.key_id == old_key).first()
        key = Key.query.filter_by(key_id = old_key).first()
        key.key = new_key
        db.session.commit()
        flash(f'Key updated successfully to app {app.name}','success')
        logger.info(f"{user.email} updated api key for application with name '{app.name}'")


    if request.method == "POST":
        app_id = request.form.get('app')
        keys = db.session.query(Key).select_from(Key).join(App).filter( App.app_id == app_id).all()
        apps = db.session.query(App).select_from(App).join(User).filter(User.user_id == user.user_id).all()

        return render_template("edit_application.html",keys = keys,apps = apps)

api/api_user/templates/api_user_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="{{url_for('static', filename = 'css/styles.css')}}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">API</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{{url_for('users.logout')}}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="{{url_for('api_user.dashboard')}}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">Interface</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Layouts
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                    <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Manage
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Application
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="{{url_for('api_user.add_application')}}">Add App</a>
                                            <a class="nav-link" href="{{url_for('api_user.edit_application')}}">Edit App</a>
                                            <a class="nav-link" href="{{url_for('users.forgot_password')}}">Forgot Password</a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Error
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">401 Page</a>
                                            <a class="nav-link" href="404.html">404 Page</a>
                                            <a class="nav-link" href="500.html">500 Page</a>
                                        </nav>
                                    </div>
                                </nav>
                            </div>
                            <div class="sb-sidenav-menu-heading">Addons</div>
                            <a class="nav-link" href="{{url_for('admin.charts')}}">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Charts
                            </a>
                            <a class="nav-link" href="{{url_for('admin.users')}}">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Tables
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        <strong>{{current_user.firstname}}</strong>&nbsp&nbsp({{current_user.user_role()}})
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                            {%with messages = get_flashed_messages(with_categories = true) %} {%if
                messages%} {%for category, message in messages%}
                <div class="alert alert-{{category}} alert-dismissible">
              <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
              <strong>{{message}}</strong>
                </div>

            {%endfor%} {%endif%} {%endwith%}
               {%block content%}
                {%endblock%}
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2022</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
<!--        INDEX SCRIPT TAGS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src ="{{url_for('static', filename = 'js/script1.js')}}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="js/datatables-simple-demo.js"></script>

<!--        USERS TABLE SCRIPT TAGS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src ="{{url_for('static', filename = 'js/script1.js')}}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src ="{{url_for('static', filename = 'js/datatables-simple-demo.js')}}"></script>


<!--   CHART TABLE SCRIPT TAGS-->
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src ="{{url_for('static', filename = 'js/script1.js')}}"</script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="assets/demo/chart-pie-demo.js"></script>
    </body>
</html>

api/api_user/templates/edit_application.html
{%extends 'api_user_base.html'%}
{%block content%}
                <main>
                    <div class="container-fluid px-4">
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="{{url_for('api_user.dashboard')}}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Edit Application/API Key</li>
                        </ol>


                        <div class="row">
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-primary text-white mb-4">
                                    <div class="card-body"> Total API keys: <h2>{{api_key_count}}</h2></h2></div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-warning text-white mb-4">
                                    <div class="card-body">Warning Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-success text-white mb-4">
                                    <div class="card-body">Success Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-danger text-white mb-4">
                                    <div class="card-body">Danger Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>




                        <div class="row">

<!--                            EDIT APPLICATION-->
                            <div class="col-xl-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-edit me-1"></i>
                                        Edit App
                                    </div>

                                    <form method = "POST" action = "{{url_for('api_user.edit_application')}}">

                                       <div class="input-group mb-3 mt-4">
                                          <select class="form-select" id="inputGroupSelect01" name="app">
                                            <option value="none">Select App</option>
                                              {%for app in apps%}
                                            <option value="{{app.app_id}}">{{app.name}}</option>
                                            {%endfor%}
                                              </select>
                                       </div>


                                        <div class="input-group mb-3 mt-4">
                                          <span class="input-group-text" id="inputGroup-sizing-default">New Name</span>
                                          <input type="text"  name = "name" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                                        </div>

                                         <div class="input-group mb-3">
                                                 <span class="input-group-text" id="inputGroup-sizing-default">New Description</span>
                                             <input type="text" name ="description" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                                         </div>


                                        <div class="d-grid gap-2 d-md-flex justify-content-md-end mr-4 mb-4">
                                          <button class="btn btn-primary" type="submit">Update App</button>
                                        </div>

                                     </form>


                                </div>
                            </div>


<!--                            EDIT API-->
                                 <div class="col-xl-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-key me-1"></i>
                                        Edit App Key
                                    </div>

                                    <form method = "POST" action = "{{url_for('api_user.edit_api_key')}}">

                                       <div class="input-group mb-3 mt-4">
                                          <select class="form-select" id="inputGroupSelect01" name="app">
                                            <option value="none">Select App</option>
                                              {%for app in apps%}
                                            <option value="{{app.app_id}}">{{app.name}}</option>
                                            {%endfor%}
                                              </select>
                                       </div>

                                        {%if keys%}
                                        {%for key in keys%}
                                        <div class="input-group mb-3 mt-4">
                                            <input class="all form-check-input" name="checkbox" type="checkbox" id="input1" value = {{key.key_id}} aria-label="...">&nbsp&nbsp&nbsp
                                             <span class="input-group-text" id="inputGroup-sizing-default">Key {{loop.index}}</span>
                                          <input class="form-control"  type="text" placeholder="{{key.key}}" readonly>
                                        </div>

                                        {%endfor%}
                                         <div class="input-group mb-3 mt-4">
                                          <span class="input-group-text" id="inputGroup-sizing-default">New Key</span>
                                          <input type="text"  value = "" name = "key" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                                        </div>

                                        <div class="d-grid gap-2 d-md-flex justify-content-md-end mr-4 mb-4">
                                          <button class="btn btn-primary" type="Submit">Save Key</button>
                                        </div>

                                        {%else%}
<!--                                         <div class="input-group mb-3 mt-4">-->
<!--                                          <select class="form-select" id="inputGroupSelect01" name="app">-->
<!--                                            <option value="none">Select App</option>-->
<!--                                              {%for app in apps%}-->
<!--                                            <option value="{{app.app_id}}">{{app.name}}</option>-->
<!--                                            {%endfor%}-->
<!--                                              </select>-->
<!--                                        </div>-->
                                        <div class="d-grid gap-2 d-md-flex justify-content-md-end mr-4 mb-4">
                                          <button class="btn btn-primary" type="Submit">Show Key</button>
                                        </div>
                                        {%endif%}
<!--                                        <div class="input-group mb-3 mt-4">-->
<!--                                          <span class="input-group-text" id="inputGroup-sizing-default">New Name</span>-->
<!--                                          <input type="text"  name = "name" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">-->
<!--                                        </div>-->

                                     </form>


                                </div>
                            </div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Applications
                            </div>
                            <div class="card-body">
                            <table id="datatablesSimple">
                                    <thead>
                                        <tr>
                                            <th  style='width:1%;'><input class="all form-check-input-sm" name="all" type="checkbox" id="input1" aria-label="..."></th>
                                            <th>App Name</th>
                                            <th>Date Created</th>
                                            <th>No of keys</th>
                                            <th>Last Request Date</th>
                                            <th>Delete</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>App Name</th>
                                            <th>Date Created</th>
                                            <th>No of keys</th>
                                            <th>Last Request Date</th>
                                            <th>Delete</th>

                                        </tr>
                                    </tfoot>
                                    <tbody>
                                    {% for r in data%}
                                        <tr>
                                             <td><input class="item form-check-input item-sm" name="checkbox" type="checkbox" id="input1"
                                                        value="{{r[0].app_id}}" aria-label="..."></td>
                                            <td>{{r[3].name}}</td>
                                            <td>{{r[3].date_created}}</td>
                                            <td>{{r[5]}}</td>
                                            <td>2022-23-23</td>
                                            <td>
                                                <a href="{{url_for('api_user.delete_app')}}" class="btn btn-danger btn-sm">
                                                    <i class="far fa-trash-alt"></i></i> Delete
                                                </a>
                                            </td>
                                        </tr>
                                    {%endfor%}


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </main>
{%endblock%}